#!/usr/bin/env bash
set -euo pipefail

# Input:
#   $1 = path to FK.json (generated by inventory_db.sh)
#   $2 = OUT_DIR (same db dir), we will write erd.dot and erd.png

FK_JSON="${1:-}"
OUT_DIR="${2:-}"
if [ -z "${FK_JSON}" ] || [ -z "${OUT_DIR}" ] || [ ! -f "${FK_JSON}" ]; then
  echo "Usage: $0 <fk_json_path> <out_dir>"
  exit 1
fi

DOT="${OUT_DIR}/erd.dot"
PNG="${OUT_DIR}/erd.png"

# Build DOT from FK JSON (simple digraph)
{
  echo "digraph ERD {"
  echo "  graph [rankdir=LR, bgcolor=white];"
  echo "  node [shape=box, style=rounded, fontname=Arial];"
  echo "  edge [color=gray50, arrowsize=0.7];"

  # Extract unique nodes
  NODES=$(jq -r '.[].source, .[].target' "${FK_JSON}" | sort -u)
  while IFS= read -r n; do
    [ -z "$n" ] && continue
    echo "  \"${n}\";"
  done <<< "$NODES"

  # Edges
  jq -r '.[] | [.source, (.source_cols|join(",")), .target, (.target_cols|join(","))] | @tsv' "${FK_JSON}" | \
  while IFS=$'\t' read -r s sc t tc; do
    label="$(printf "%s → %s" "$sc" "$tc")"
    echo "  \"$s\" -> \"$t\" [label=\"$label\", fontsize=9];"
  done

  echo "}"
} > "${DOT}"

# Render PNG (requires graphviz)
dot -Tpng "${DOT}" -o "${PNG}" || true
echo "ERD generated: ${PNG}"
